version: '3.8'
services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: fhiruser
      POSTGRES_PASSWORD: fhirpassword
      POSTGRES_DB: fhirdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fhiruser", "-d", "fhirdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: valkey/valkey:8.0
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DB_URL: postgres://fhiruser:fhirpassword@db:5432/fhirdb?sslmode=disable
      CACHE_URL: cache:6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

volumes:
  postgres_data: